name: test_flutter_v2
description: "Licenta"
publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0
  firebase_database: ^11.0.0
  flutter_local_notifications: ^17.1.2
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.2.1
  sleek_circular_slider: ^2.0.1
  flutter_speed_dial: ^7.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/favIconShieldSnap.jpg"

dependency_overrides:
  web: ^0.5.1

flutter:
  assets:
    - assets/images/welcomepage.png
    - assets/images/favIconShieldSnap.jpg
    - assets/images/logo_Google.png

  uses-material-design: true
